name: Build

on: 
  push:
  pull_request:

jobs:
  Ruff:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]
    steps:
      - name: â¤µï¸ Checkout repository
        uses: actions/checkout@v6
      - name: ğŸ— Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: ğŸ— Install ruff
        run: python -m pip install --upgrade pip ruff
      - name: ğŸ” Analyse with ruff
        run: ruff check .
