name: Type

on:
  push:
    branches:
      - main
  pull_request:

env:
  DEFAULT_PYTHON: 3.13

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - name: â¤µï¸ Checkout repository
        uses: actions/checkout@v6
      - name: ğŸ— Set up Python ${{ env.DEFAULT_PYTHON }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}
      - name: ğŸ— Install uv
        uses: astral-sh/setup-uv@v7
      - name: ğŸ— Install mypy
        run: uv sync --locked
      - name: ğŸš€ Run mypy
        run: uv tool run mypy .
